### ISSUE TITLE
Create tb-aws-dac repo (Fork from tb-gcp-dac)

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/TranquilityBase#32]
### This issue is part of the "Eagle Console - AWS LandingZone" Milestone

**Comment by RDHA-GFT** [comment]
Hi Fabio, Do you just want a new tb-aws-dac repo created or does this need to be a clone or fork of the code which is in tb-gcp-dac?

If so not sure the best way to fork the tb-gcp-dac code into a new rep under tranquilitybase-io\ ?

**Comment by Salles-FA** [comment]
Hi Richard,

As we've spoken earlier today, just the new repo. 

Thanks!

**Comment by RDHA-GFT** [comment]
Created new repo: https://github.com/tranquilitybase-io/tb-aws-dac
