### ISSUE TITLE
Create tb-aws-dac docker image and add to AWS Eagle Console kubernetes cluster

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/TranquilityBase#33]
### This issue is part of the "Eagle Console - AWS LandingZone" Milestone

**Comment by Tirano2150** [comment]
A working DAC has been created and is currently hosted at 122072647213.dkr.ecr.eu-west-1.amazonaws.com/dac.

There will need to be changes to this DAC to fully implement the system, such as creating the repo however this will be covered in other tickets as it is a large piece of work
