### ISSUE TITLE
Agree the individual structure of each Repo wiki

### ISSUE THREAD

**Issue by harshana-hafd** [tranquilitybase-io/TranquilityBase#6]
We need to agree the structure of each individual repo to ensure consistency.

**Option A**
Per GCP LZ  technical design document
1.	Home 
2.	Cloud Identity
3.	Organisation
4.	IAM
5.	Networking
6.	Logging, Monitoring and Auditing
7.	Billing
8.	Security
9.	Infrastructure as a code

**Option B**
Per AWS LZ TB repo readme 
1.	Overview
2.	Organization
3.	Organization, organizations units and accounts
4.	Core Organization Unit and its core components anatomy
5.	Generic account anatomy
6.	Account Creation in LZ
7.	Code Blueprints
8.	Infrastucure as code Development
9.	Directory Structure
10.	Local / Remote Execution sequence steps
11.	Coding standards and naming conventions
12.	Modules
13.	Module references
14.	Module dependencies

**Option C**
Do we want to have an Intro/overview repo and have all documentation link to this?

**Comment by dominique-castel** [comment]
Latest provisional structure: 
1)	TranquilityBase -overview repo
2)	tb-activators 
a.	Do we have one activator repo or do we have multiple (e.g. one for each cloud?)
b.	Have we configured how they will download into Houston?
3)	tb-eagle-console -  User Interface (UI)
4)	tb-houston-service – User Interface Backend
5)	tb-gcp-lz (the old tb-gcp) - Landing Zone  
a.	For the name for items 5 to 10 to we want 
i.	tb-gcp (as currently in github)
ii.	tb-gcp-lz (suggested by Andrew)
iii.	tb-lz-gcp
6)	tb-gcp-dac  -  GCP Backend  
7)	tb-aws-lz        -  AWS Landing Zone
8)	tb-aws-dac     -  AWS Backend
9)	tb-azure-lz      - Azure Landing Zone
10)	tb-azure-dac   - Azure Backend
delete tb-eaglet.

Scott and Richard will agree on repo naming convention with Ricardo and Naresh.

**Comment by dominique-castel** [comment]
It has been agreed with Andrew R on 2nd/04 that before we applied any change to other cloud environment documentation, we ensure that the tb-gcp documentation and architecture is mature enough.
