### ISSUE TITLE
No license listed for this repo

### ISSUE THREAD

**Issue by andrewvieyra** [tranquilitybase-io/TranquilityBase#60]
Hello!

I see some of the other Tranquility Base repos have the Apache 2.0 license in them, but this one does not.

It would be great for customers if the appopriate licence is applied consistently across all the associated repos so that an entity wishing to deploy it can do so in confidence

**Comment by Salles-FA** [comment]
Hi @andrewvieyra ,

Thank you! I'm now reviewing all public repos.
